using System.Reflection;
using RimWorld;
using Verse;

namespace UniqueWeaponsUnbound
{
    /// <summary>
    /// Transforms a weapon Thing into a different ThingDef while preserving
    /// identity-bearing properties: quality, hitpoint percentage, texture
    /// override, and (when applicable) Ideology relic status. Used during
    /// customization at the 0↔1 trait boundary to swap between a weapon's
    /// base def and its unique counterpart.
    /// </summary>
    [StaticConstructorOnStartup]
    public static class WeaponDefConversion
    {
        // Ideology DLC: Precept_Relic.generatedRelic (private Thing).
        // Resolved once at startup; null if Ideology is not installed.
        // A null value when Ideology IS installed means the field surface has
        // drifted — the static ctor below logs that as an error so a silently
        // stale relic→thing pointer doesn't corrupt a relic during def
        // conversion (see TransferRelicStatus).
        private static readonly FieldInfo GeneratedRelicField =
            GenTypes.GetTypeInAnyAssembly("RimWorld.Precept_Relic")
                ?.GetField("generatedRelic", BindingFlags.NonPublic | BindingFlags.Instance);

        static WeaponDefConversion()
        {
            if (ModsConfig.IdeologyActive && GeneratedRelicField == null)
            {
                Log.Error("[Unique Weapons Unbound] Ideology active but "
                    + "Precept_Relic.generatedRelic could not be resolved via reflection; "
                    + "relic-flagged weapons that undergo a base<->unique def conversion "
                    + "during customization will leave the precept pointing at the "
                    + "destroyed pre-conversion weapon. RimWorld API may have changed.");
            }
        }

        /// <summary>
        /// Creates a new weapon Thing from targetDef, copying quality and hitpoints
        /// from oldWeapon. If targetDef has CompUniqueWeapon (base→unique conversion),
        /// clears the auto-generated traits/name/color from PostPostMake().
        /// Returns the new weapon. Does NOT destroy oldWeapon (caller's responsibility).
        /// </summary>
        public static Thing ConvertWeaponDef(Thing oldWeapon, ThingDef targetDef)
        {
            Thing newWeapon = ThingMaker.MakeThing(targetDef);

            // Copy quality
            if (oldWeapon.TryGetQuality(out QualityCategory quality))
            {
                CompQuality qualityComp = newWeapon.TryGetComp<CompQuality>();
                qualityComp?.SetQuality(quality, ArtGenerationContext.Colony);
            }

            // Copy hitpoints as a percentage of max
            if (oldWeapon.MaxHitPoints > 0 && newWeapon.MaxHitPoints > 0)
            {
                float hpPct = (float)oldWeapon.HitPoints / oldWeapon.MaxHitPoints;
                newWeapon.HitPoints = (int)(newWeapon.MaxHitPoints * hpPct);
                if (newWeapon.HitPoints < 1)
                    newWeapon.HitPoints = 1;
            }

            // Copy texture index
            newWeapon.overrideGraphicIndex = oldWeapon.overrideGraphicIndex;

            // Scrub the random state PostPostMake leaves on a fresh unique weapon
            // (trait list, name, color, accuracy-malus cache, and any equippable-
            // ability comp wiring from a rolled ability trait). See the helper
            // for the full rationale — without the ability-comp scrub, abilities
            // from auto-rolled traits like SmokeLauncher persist as phantom
            // gizmos even after the trait list is cleared.
            WeaponModificationUtility.ClearAutoGeneratedUniqueState(newWeapon);

            return newWeapon;
        }

        /// <summary>
        /// Transfers Ideology relic status from the old weapon to the new weapon.
        /// Must be called BEFORE destroying the old weapon — clears the old weapon's
        /// StyleSourcePrecept so that Thing.Destroy() does not fire Notify_ThingLost,
        /// which would trigger RelicDestroyed events, mood debuffs, and permanently
        /// orphan the relic precept.
        ///
        /// Updates both sides of the bidirectional reference:
        ///   Thing.StyleSourcePrecept → Precept_Relic (via CompStyleable)
        ///   Precept_Relic.generatedRelic → Thing (via reflection)
        ///
        /// No-op if Ideology is not active or the weapon is not a relic.
        /// </summary>
        public static void TransferRelicStatus(Thing oldWeapon, Thing newWeapon)
        {
            if (!ModsConfig.IdeologyActive)
                return;

            Precept_ThingStyle precept = oldWeapon.StyleSourcePrecept;
            if (precept == null)
                return;

            // Clear from old weapon BEFORE it gets destroyed to prevent
            // Precept_Relic.Notify_ThingLost from firing RelicDestroyed/RelicLost events.
            oldWeapon.StyleSourcePrecept = null;

            // Pre-seed the new weapon's CompStyleable state from the old weapon
            // before the StyleSourcePrecept setter runs below.
            //
            // styleDef: the SourcePrecept setter only writes styleDef when the
            // new def's randomStyleChance is 0 AND the ideo has a style mapping
            // for the new def. Either condition failing leaves the new weapon
            // styleless after conversion. Copying first preserves the visual
            // continuity; the setter still overwrites our copy when it has a
            // valid ideo-driven answer for the new def.
            //
            // everSeenByPlayer: the setter never touches this, so the copy is
            // strictly additive. Direct field assignment rather than
            // SetEverSeenByPlayer so we don't re-fire Notify_RelicSeenByPlayer
            // (which would spam the "relics collected" letter on every
            // customization of an already-seen relic).
            if (oldWeapon is ThingWithComps oldTwc && newWeapon is ThingWithComps newTwc
                && oldTwc.compStyleable != null && newTwc.compStyleable != null)
            {
                newTwc.compStyleable.styleDef = oldTwc.compStyleable.styleDef;
                newTwc.compStyleable.everSeenByPlayer = oldTwc.compStyleable.everSeenByPlayer;
            }

            // Point the new weapon back at the precept. The setter may overwrite
            // the styleDef we just copied via ideo.style.StyleForThingDef for
            // the new def — that's the right behavior when the lookup succeeds.
            newWeapon.StyleSourcePrecept = precept;

            // Update the Precept_Relic's private generatedRelic field to point
            // at the new weapon instance, keeping the precept→thing reference valid.
            if (GeneratedRelicField != null && precept is Precept_Relic)
            {
                GeneratedRelicField.SetValue(precept, newWeapon);
            }
        }
    }
}
